[toolchain]
channel = "1.83.0"
components = [ "rustc", "rustfmt", "clippy" ]
targets = [ "x86_64-unknown-linux-gnu", "aarch64-unknown-linux-gnu", "x86_64-apple-darwin", "aarch64-apple-darwin", "x86_64-pc-windows-msvc" ]
profile = "minimal"
